apiVersion: module-deployment.serverless.alipay.com/v1alpha1
kind: Module
metadata:
  labels:
    app.kubernetes.io/name: module
    app.kubernetes.io/instance: module-sample
    app.kubernetes.io/part-of: module-deployment
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: module-deployment
  name: module-sample
spec:
  # TODO(user): Add fields here
