apiVersion: serverless.alipay.com/v1alpha1
kind: ModuleDeployment
metadata:
  labels:
    app.kubernetes.io/name: moduledeployment
    app.kubernetes.io/instance: moduledeployment-sample
    app.kubernetes.io/part-of: module-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: module-controller
  name: moduledeployment-sample-facade
spec:
  baseDeploymentName: dynamic-stock-deployment
  template:
    spec:
      module:
        name: dynamic-facade
        version: '1.0.0'
        url: http://serverless-opensource.oss-cn-shanghai.aliyuncs.com/module-packages/stable/dynamic-facade-1.0.0-ark-biz.jar
  replicas: 1
  operationStrategy:
    needConfirm: true
    useBeta: false
    batchCount: 1
    upgradePolicy: uninstall_then_install
  schedulingStrategy:
    schedulingPolicy: scatter

