apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-controller
  labels:
    app: module-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module-controller
  template:
    metadata:
      labels:
        app: module-controller
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: module-controller
          image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/test/module-controller:v0.5
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
