name: Koupleless Samples Formatter and Test
run-name: ${{ github.actor }} pushed code

on:
  push:
    branches:
      - main
      - 2.0.x
      - 2.1.x
    paths:
      - 'koupleless-runtime/**'
      - 'samples/**'

  pull_request:
    branches:
      - main
      - 2.0.x
      - 2.1.x
    paths:
      - 'koupleless-runtime/**'
      - 'samples/**'

  # enable manually running the workflow
  workflow_dispatch:

jobs:
  unit-test-for-springboot-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 8
          cache: maven

      - name: Update Maven version to 3.9.x to enable cross bundle without install
        env:
          MAVEN_VERSION: '3.9.5'
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Test for springboot samples
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -am -B -U
        working-directory: samples/springboot-samples/

      - name: Check code formatter
        run: sh ./check_format.sh
        working-directory: koupleless-runtime

  unit-test-for-sofaboot-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 8
          cache: maven

      - name: Update Maven version to 3.9.x to enable cross bundle without install
        env:
          MAVEN_VERSION: '3.9.5'
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Test for sofaboot samples
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -am -B -U
        working-directory: samples/sofaboot-samples

      - name: Check code formatter
        run: sh ./check_format.sh
        working-directory: koupleless-runtime

  unit-test-for-dubbo-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 8
          cache: maven

      - name: Update Maven version to 3.9.x to enable cross bundle without install
        env:
          MAVEN_VERSION: '3.9.5'
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Test for dubbo samples
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -am -B -U
        working-directory: samples/dubbo-samples

      - name: Check code formatter
        run: sh ./check_format.sh
        working-directory: koupleless-runtime

  unit-test-for-springboot3-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: maven

      - name: Update Maven version to 3.9.x to enable cross bundle without install
        env:
          MAVEN_VERSION: '3.9.5'
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Install Runtime
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -am -B -U
        working-directory: koupleless-runtime

      - name: Test for springboot3 samples
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -am -B -U
        working-directory: samples/springboot3-samples

      - name: Check code formatter
        run: sh ./check_format.sh
        working-directory: koupleless-runtime
